In [1]:
# We import pandas because it helps us read and work with table data easily.
import pandas as pd

In [2]:
# We read the iris.csv file and store it in a dataframe named df.
# A dataframe is like a table of rows and columns.
df = pd.read_csv("iris.csv")

In [3]:
# head() shows the first 5 rows.
# We use it to quickly see how our dataset looks.
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
# tail() shows the last 5 rows.
# We use it to check the ending part of the dataset.
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
# shape tells us the size of the dataset.
# It gives number of rows and number of columns.
df.shape

(150, 6)

In [6]:
# columns shows all column names in the dataset.
# We use it to know what data is available.
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

## 4. Data Preprocessing
Here we check the data before using it.
We look for missing values, duplicate rows, data types, and basic statistics.

In [7]:
# isnull().sum() counts missing values in each column.
# We use it to know if any data is empty.
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [8]:
# duplicated().sum() counts repeated rows.
# We use it to check whether the same row appears more than once.
df.duplicated().sum()

np.int64(0)

In [9]:
# info() gives a quick summary of the dataset.
# It shows column names, non-null values, and data types.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [10]:
# describe() gives basic statistics for numeric columns.
# It shows count, mean, min, max, and more.
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

## 5. Data Selection
Here we learn how to select specific rows and columns from the dataset.

In [11]:
# This selects only one column named SepalLengthCm.
# We use it when we want data from a single column.
df["SepalLengthCm"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [12]:
# This shows rows from index 0 to 4.
# We use slicing to get a small part of the dataset.
df[0:5]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
# loc selects columns by their names.
# Here we take only PetalLengthCm and PetalWidthCm.
df.loc[:, ["PetalLengthCm","PetalWidthCm"]]

     PetalLengthCm  PetalWidthCm
0              1.4           0.2
1              1.4           0.2
2              1.3           0.2
3              1.5           0.2
4              1.4           0.2
..             ...           ...
145            5.2           2.3
146            5.0           1.9
147            5.2           2.0
148            5.4           2.3
149            5.1           1.8

[150 rows x 2 columns]

In [14]:
# iloc selects rows and columns by index numbers.
# Here we take first 5 rows and first 2 columns.
df.iloc[0:5, 0:2]

   Id  SepalLengthCm
0   1            5.1
1   2            4.9
2   3            4.7
3   4            4.6
4   5            5.0

In [15]:
# dtypes shows the data type of each column.
# We use it to check whether the data is integer, float, or object.
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

## 7. Data Normalization
Normalization changes values to a common scale.
We use it so large values and small values become easier to compare.

In [16]:
# We import MinMaxScaler to scale numeric values between 0 and 1.
from sklearn.preprocessing import MinMaxScaler

# These are the numeric columns we want to normalize.
cols = ["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]

# We create the scaler object.
scaler = MinMaxScaler()

# fit_transform() learns the min and max values and scales the data.
# Then we store the normalized values back into the same columns.
df[cols] = scaler.fit_transform(df[cols])
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1       0.222222      0.625000       0.067797      0.041667  Iris-setosa
1   2       0.166667      0.416667       0.067797      0.041667  Iris-setosa
2   3       0.111111      0.500000       0.050847      0.041667  Iris-setosa
3   4       0.083333      0.458333       0.084746      0.041667  Iris-setosa
4   5       0.194444      0.666667       0.067797      0.041667  Iris-setosa

In [17]:
# After normalization, min() checks the smallest value in each selected column.
# It should be close to 0.
df[cols].min()

SepalLengthCm    0.0
SepalWidthCm     0.0
PetalLengthCm    0.0
PetalWidthCm     0.0
dtype: float64

In [18]:
# max() checks the largest value in each selected column.
# It should be close to 1.
df[cols].max()

SepalLengthCm    1.0
SepalWidthCm     1.0
PetalLengthCm    1.0
PetalWidthCm     1.0
dtype: float64

## 8. Convert Categorical Data (Species)
The Species column has text values.
Machines understand numbers better, so we convert these categories into numbers.

In [19]:
# unique() shows all different category names in Species.
# We use it to see the possible flower classes.
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [21]:
# We import LabelEncoder to convert text labels into numbers.
from sklearn.preprocessing import LabelEncoder
 
 # We create the label encoder object.
label_encoder = LabelEncoder()
 
 # We make a copy so the original df stays safe.
df_label = df.copy()
 
 # fit_transform() gives a number to each Species value.
 # This is the function that changes flower names into 0, 1, and 2.
 # Example: Iris-setosa may become 0, Iris-versicolor may become 1, and Iris-virginica may become 2.
df_label['Species'] = label_encoder.fit_transform(df_label['Species'])

In [22]:
# head() shows the first 5 rows after label encoding.
# Now Species is shown as numbers instead of text.
df_label.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1       0.222222      0.625000       0.067797      0.041667        0
1   2       0.166667      0.416667       0.067797      0.041667        0
2   3       0.111111      0.500000       0.050847      0.041667        0
3   4       0.083333      0.458333       0.084746      0.041667        0
4   5       0.194444      0.666667       0.067797      0.041667        0

In [23]:
# unique() now shows the encoded class values.
# We expect values like 0, 1, and 2.
df_label['Species'].unique()

array([0, 1, 2])

## 9. One-Hot Encoding
One-hot encoding makes separate columns for each category.
It helps represent categories without keeping them in one single numeric column.

In [24]:
# get_dummies() creates separate columns from the Species column.
 # This is the function that creates True and False values.
 # If a row belongs to Species_0, then Species_0 becomes True and the other species columns become False.
 # Because Species has 0, 1, and 2, it creates Species_0, Species_1, and Species_2.
df_encoded = pd.get_dummies(df_label, columns=['Species'])
 
 # head() shows the first 5 rows after one-hot encoding.
df_encoded.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_0,Species_1,Species_2
0,1,0.222222,0.625000,0.067797,0.041667,True,False,False
1,2,0.166667,0.416667,0.067797,0.041667,True,False,False
2,3,0.111111,0.500000,0.050847,0.041667,True,False,False
3,4,0.083333,0.458333,0.084746,0.041667,True,False,False
4,5,0.194444,0.666667,0.067797,0.041667,True,False,False

In [25]:
# Here we display only the one-hot encoded columns.
# True means the row belongs to that class. False means it does not.
df_encoded[['Species_0', 'Species_1', 'Species_2']].head()

   Species_0  Species_1  Species_2
0       True      False      False
1       True      False      False
2       True      False      False
3       True      False      False
4       True      False      False

In [27]:
# We make one more copy to convert True/False into 1/0.
df_encoded_int = df_encoded.copy()
 
 # astype(int) is the function that changes True to 1 and False to 0.
 # This gives the same one-hot result in integer form.
df_encoded_int[['Species_0', 'Species_1', 'Species_2']] = df_encoded_int[['Species_0', 'Species_1', 'Species_2']].astype(int)
 
 # Now we display the integer one-hot encoded columns.
df_encoded_int[['Species_0', 'Species_1', 'Species_2']].head()

   Species_0  Species_1  Species_2
0          1          0          0
1          1          0          0
2          1          0          0
3          1          0          0
4          1          0          0