In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = {
    "Name" : ["A","B","C","D","E"],
    "Marks" : [90,45,500,None,49],
    "Attendance" : [89,49,77,89,None]
}
df= pd.DataFrame(data)
df

  Name  Marks  Attendance
0    A   90.0        89.0
1    B   45.0        49.0
2    C  500.0        77.0
3    D    NaN        89.0
4    E   49.0         NaN

In [3]:
df.describe()

            Marks  Attendance
count    4.000000    4.000000
mean   171.000000   76.000000
std    220.274072   18.867962
min     45.000000   49.000000
25%     48.000000   70.000000
50%     69.500000   83.000000
75%    192.500000   89.000000
max    500.000000   89.000000

In [4]:
#Check Missing Values
print(df.isnull().sum())

Name          0
Marks         1
Attendance    1
dtype: int64

In [5]:
df.dtypes

Name              str
Marks         float64
Attendance    float64
dtype: object

In [6]:
#Handle Missing Values
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())

print(df)

  Name  Marks  Attendance
0    A   90.0        89.0
1    B   45.0        49.0
2    C  500.0        77.0
3    D  171.0        89.0
4    E   49.0        83.0

In [7]:
#Handle Inconsistencies
df['Marks'] = df['Marks'].astype(int)

df['Attendance'] = df['Attendance'].astype(int)

print(df.dtypes)

Name            str
Marks         int64
Attendance    int64
dtype: object

In [8]:
df.isnull().sum()

Name          0
Marks         0
Attendance    0
dtype: int64

In [9]:

df

  Name  Marks  Attendance
0    A     90          89
1    B     45          49
2    C    500          77
3    D    171          89
4    E     49          83

In [10]:
# Identify Outliers Using IQR Method

Q1 = df['Marks'].quantile(0.25)

Q3 = df['Marks'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR

upper_limit = Q3 + 1.5 * IQR

outliers = df[(df['Marks'] < lower_limit) | (df['Marks'] > upper_limit)]

print("Lower Limit :", lower_limit)

print("Upper Limit :", upper_limit)

print("\nOutliers")

print(outliers)

Lower Limit : -134.0
Upper Limit : 354.0

Outliers
  Name  Marks  Attendance
2    C    500          77

In [11]:
#Apply Log Transformation
df['Marks_Log'] = np.log(df['Marks'])

print(df)

  Name  Marks  Attendance  Marks_Log
0    A     90          89   4.499810
1    B     45          49   3.806662
2    C    500          77   6.214608
3    D    171          89   5.141664
4    E     49          83   3.891820

In [12]:
#Apply Normalization
df['Marks_Normalized'] = (df['Marks'] - df['Marks'].min()) / (df['Marks'].max() - df['Marks'].min())

print(df)

  Name  Marks  Attendance  Marks_Log  Marks_Normalized
0    A     90          89   4.499810          0.098901
1    B     45          49   3.806662          0.000000
2    C    500          77   6.214608          1.000000
3    D    171          89   5.141664          0.276923
4    E     49          83   3.891820          0.008791

In [13]:
#Apply Scaling
scaler = MinMaxScaler()

df[['Marks_Scaled']] = scaler.fit_transform(df[['Marks']])

print(df)

  Name  Marks  Attendance  Marks_Log  Marks_Normalized  Marks_Scaled
0    A     90          89   4.499810          0.098901      0.098901
1    B     45          49   3.806662          0.000000      0.000000
2    C    500          77   6.214608          1.000000      1.000000
3    D    171          89   5.141664          0.276923      0.276923
4    E     49          83   3.891820          0.008791      0.008791

In [14]:
print(df)

  Name  Marks  Attendance  Marks_Log  Marks_Normalized  Marks_Scaled
0    A     90          89   4.499810          0.098901      0.098901
1    B     45          49   3.806662          0.000000      0.000000
2    C    500          77   6.214608          1.000000      1.000000
3    D    171          89   5.141664          0.276923      0.276923
4    E     49          83   3.891820          0.008791      0.008791